#!/usr/bin/env bash
# build_tcl_lib.sh — phase 9.4.2.b build recipe.
#
# Compiles src/tests/tcl/libpassqlite3tcl.lpr into a shared object at
# bin/libpassqlite3tcl.so.  `tclsh` can then `load` it as a Tcl
# package (entry point Sqlite3_Init).
#
# This is intentionally separate from build.sh: the loadable package
# does not link against the full passqlite3*.pas tree yet — only the
# minimal Tcl bridge + the Sqlite3_Init stub.  Real DbMain wiring
# lands in 9.4.2.c..f and will pull in passqlite3main / codegen / etc.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC_DIR="$SCRIPT_DIR/.."
ROOT_DIR="$SRC_DIR/.."
BIN_DIR="$ROOT_DIR/bin"
TCL_DIR="$SCRIPT_DIR/tcl"

mkdir -p "$BIN_DIR"

# Opt-in pre-update hook support: `PREUPDATE=1 ./build_tcl_lib.sh` adds
# -dSQLITE_ENABLE_PREUPDATE_HOOK so the engine pre-update API and the
# `db preupdate` Tcl subcommand are compiled in.  Off by default
# (matches build.sh and the upstream oracle build).
PREUPDATE_FLAGS=()
if [ "${PREUPDATE:-0}" = "1" ]; then
  echo "PREUPDATE=1 — passing -dSQLITE_ENABLE_PREUPDATE_HOOK to fpc."
  PREUPDATE_FLAGS=(-dSQLITE_ENABLE_PREUPDATE_HOOK)
fi

# Opt-in unlock-notify support: `UNLOCK_NOTIFY=1 ./build_tcl_lib.sh` adds
# -dSQLITE_ENABLE_UNLOCK_NOTIFY so the engine notify.c port and the
# `db unlock_notify` Tcl subcommand are compiled in.  Off by default
# (matches build.sh and the upstream oracle build).
UNLOCK_NOTIFY_FLAGS=()
if [ "${UNLOCK_NOTIFY:-0}" = "1" ]; then
  echo "UNLOCK_NOTIFY=1 — passing -dSQLITE_ENABLE_UNLOCK_NOTIFY to fpc."
  UNLOCK_NOTIFY_FLAGS=(-dSQLITE_ENABLE_UNLOCK_NOTIFY)
fi

# -Fu paths:
#   $TCL_DIR  : PasTclBridge.pas, PasTclSqlite.pas
#   $SRC_DIR  : passqlite3types.pas (for SQLITE_VERSION constant)
# -FU/-FE   : .ppu/.o + final binary into bin/
# -k-ltcl8.6 -k-ldl : link Tcl + dlopen runtime
# Output .so name pinned via -o.
# -dSQLITE_TEST enables the {$ifdef SQLITE_TEST} I/O-error injection
# instrumentation in passqlite3os.pas (task 9.4.7.c) and the test2.c
# counter wiring in TestModuleIoerr.  The default engine build (build.sh)
# does NOT pass this, so the production .so stays byte-for-byte unaffected.
# -dSQLITE_NO_SYNC mirrors the upstream testfixture link (main.mk:1797
# passes -DSQLITE_NO_SYNC=1): full_fsync becomes an fstat-only no-op
# (os_unix.c:3810..3814) so WAL-heavy tests (e_walauto etc.) are not
# bound by real disk fsync latency.  The SQLITE_TEST sync counters
# still increment.  Production builds never define this.
FPC_CMD=(fpc
  -MObjFPC -Scghi -O1
  -Cg
  -dSQLITE_TEST
  -dSQLITE_NO_SYNC
  "${PREUPDATE_FLAGS[@]}"
  "${UNLOCK_NOTIFY_FLAGS[@]}"
  -Fu"$TCL_DIR"
  -Fu"$TCL_DIR/testmodules"
  -Fu"$SRC_DIR"
  -Fi"$SRC_DIR"
  -FU"$BIN_DIR"
  -FE"$BIN_DIR"
  -o"$BIN_DIR/libpassqlite3tcl.so"
  -k-ltcl8.6 -k-ldl -k-lm -k-lz
  "$TCL_DIR/libpassqlite3tcl.lpr")

echo "+ ${FPC_CMD[*]}"
"${FPC_CMD[@]}"

echo "+ file $BIN_DIR/libpassqlite3tcl.so"
file "$BIN_DIR/libpassqlite3tcl.so"

# 9.4.7.h — emit a Tcl pkgIndex.tcl next to the .so so that, once bin/ is
# on the interpreter's ::auto_path, a bare `package require sqlite3`
# transparently loads the package (no explicit `load` needed).  The
# package name + version mirror Tcl_PkgProvide in PasTclSqlite.pas
# (`sqlite3` / SQLITE_VERSION).  $dir is supplied by Tcl as the directory
# containing this pkgIndex.tcl, so the .so reference stays relocatable.
PKG_VERSION="$(grep -oE "SQLITE_VERSION[[:space:]]*=[[:space:]]*'[0-9.]+'" \
  "$SRC_DIR/passqlite3types.pas" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+" | head -1)"
PKG_VERSION="${PKG_VERSION:-3.53.0}"
PKG_INDEX="$BIN_DIR/pkgIndex.tcl"
cat > "$PKG_INDEX" <<EOF
# pkgIndex.tcl — generated by src/tests/build_tcl_lib.sh (phase 9.4.7.h).
# Put this directory on ::auto_path, then \`package require sqlite3\`.
package ifneeded sqlite3 $PKG_VERSION \\
    [list load [file join \$dir libpassqlite3tcl.so] Sqlite3]
EOF
echo "+ wrote $PKG_INDEX (sqlite3 $PKG_VERSION)"
cat "$PKG_INDEX"

# Emit a Tcl autoload index so a plain tclsh on this dir's TCLLIBPATH auto-loads
# the bare `sqlite3` command the first time it is used. pragma3.test spawns a
# child interpreter via `exec [info nameofexecutable] script.txt` that calls
# `sqlite3` with no preceding `package require` (it relies on the upstream
# testfixture having sqlite3 built in); this index gives the same behaviour.
AUTOLOAD="$BIN_DIR/sqlite3_autoload.tcl"
cat > "$AUTOLOAD" <<EOF
# Auto-loaded by tclIndex the first time the bare \`sqlite3\` command is used in
# a child interpreter. Loads the passqlite3 Tcl package, which registers the
# real \`sqlite3\` command; Tcl's auto_load then re-dispatches the original call.
package require sqlite3
EOF
TCL_INDEX="$BIN_DIR/tclIndex"
cat > "$TCL_INDEX" <<'EOF'
# Tcl autoload index file, version 2.0
set auto_index(sqlite3) [list source [file join $dir sqlite3_autoload.tcl]]
EOF
echo "+ wrote $TCL_INDEX + $AUTOLOAD"
