{
  SPDX-License-Identifier: blessing

  The author disclaims copyright to this source code.  In place of
  a legal notice, here is a blessing:

     May you do good and not evil.
     May you find forgiveness for yourself and forgive others.
     May you share freely, never taking more than you give.

  ------------------------------------------------------------------------

  This work is dedicated to all human kind, and also to all non-human kinds.

  This is a faithful port of SQLite 3.53 (https://sqlite.org/) from C to
  Free Pascal, authored by Dr. Joao Paulo Schwarz Schuler and contributors
  (see commit history).
}
{$I ../passqlite3.inc}
program TestFts3Expr;

{
  Phase 6.40.1.i gate — the FTS3 MATCH query-expression parser
  (fts3_expr.c: sqlite3Fts3ExprParse / fts3ExprParse / getNextNode /
  getNextToken / getNextString / fts3ExprBalance / sqlite3Fts3ExprFree).

  The engine build (build.sh) does NOT define SQLITE_TEST, so the
  fts3_exprtest SQL function is not registered.  This gate instead drives
  the public parser API (sqlite3Fts3ExprParse) directly and serialises the
  resulting Fts3Expr tree with a local copy of fts3_expr.c's exprToString()
  (the same text contract the SQLITE_TEST fts3_exprtest function exposes).

  SYNTAX MODE: the engine compiles the new/parenthesis syntax
  (sqlite3_fts3_enable_parentheses = 1), matching the oracle .so which is
  built WITH SQLITE_ENABLE_FTS3_PARENTHESIS.  The expected serialisations
  below were generated by compiling the C amalgamation with
  -DSQLITE_TEST -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS,
  setting sqlite3_fts3_enable_parentheses=1, and running fts3_exprtest /
  fts3_exprtest_rebalance.

  Exit 0 = PASS.
}

uses
  ctypes,
  SysUtils,
  passqlite3types,
  passqlite3util,
  passqlite3printf,
  passqlite3os,
  passqlite3vdbe,
  passqlite3vtab,
  passqlite3main,
  passqlite3fts3;

var
  g_fail: Integer = 0;

procedure Check(cond: Boolean; const msg: string);
begin
  if not cond then begin
    WriteLn('FAIL: ', msg);
    Inc(g_fail);
  end;
end;

{ A Pascal mirror of fts3_expr.c:1146..1187 exprToString().  Returns a
  Pascal string (the C uses a malloc'd buffer; the rendered byte content
  is identical). }
function ExprToStr(pExpr: PFts3Expr): string;
var
  pPhrase: PFts3Phrase;
  pTok: PFts3PhraseToken;
  i: cint;
  tokTxt: string;
begin
  if pExpr = nil then Exit('');
  case pExpr^.eType of
    FTSQUERY_PHRASE: begin
      pPhrase := pExpr^.pPhrase;
      Result := 'PHRASE ' + IntToStr(pPhrase^.iColumn) + ' 0';
      for i := 0 to pPhrase^.nToken - 1 do begin
        { aToken[i] — FLEXARRAY access. }
        pTok := @PFts3PhraseToken(@pPhrase^.aToken[0])[i];
        SetLength(tokTxt, pTok^.n);
        if pTok^.n > 0 then
          Move(pTok^.z^, tokTxt[1], pTok^.n);
        Result := Result + ' ' + tokTxt;
        if pTok^.isPrefix <> 0 then Result := Result + '+';
      end;
      Exit;
    end;
    FTSQUERY_NEAR: Result := 'NEAR/' + IntToStr(pExpr^.nNear) + ' ';
    FTSQUERY_NOT:  Result := 'NOT ';
    FTSQUERY_AND:  Result := 'AND ';
    FTSQUERY_OR:   Result := 'OR ';
  else
    Result := '';
  end;
  Result := Result + '{' + ExprToStr(pExpr^.pLeft) + '} {'
                   + ExprToStr(pExpr^.pRight) + '}';
end;

{ The engine keeps its tokenizer hash private (inside the Fts3HashWrapper
  attached to the fts3_tokenizer FuncDef).  To exercise the parser we build
  our own hash + load the built-in "simple"/"porter" tokenizers — the same
  set sqlite3Fts3Init loads — then call sqlite3Fts3ExprParse with a
  tokenizer resolved from it. }
var
  g_hash: TFts3Hash;
  g_simple, g_porter: Psqlite3_tokenizer_module;

procedure InitHash;
begin
  sqlite3Fts3HashInit(@g_hash, FTS3_HASH_STRING, 1);
  sqlite3Fts3SimpleTokenizerModule(@g_simple);
  sqlite3Fts3PorterTokenizerModule(@g_porter);
  sqlite3Fts3HashInsert(@g_hash, PChar('simple'), 7, g_simple);
  sqlite3Fts3HashInsert(@g_hash, PChar('porter'), 7, g_porter);
end;

procedure DoParse(const zTok, zExpr: string; const cols: array of string;
  bRebalance: Boolean; const zExpected: string);
var
  pTokenizer: Psqlite3_tokenizer;
  azCol: array[0..7] of PChar;
  colBuf: array[0..7] of AnsiString;
  nCol, i, rc: cint;
  pExpr: PFts3Expr;
  zErr: PChar;
  zTokC, zExprC: AnsiString;
  got: string;
begin
  pTokenizer := nil;
  pExpr := nil;
  zErr := nil;
  zTokC := zTok + #0;
  zExprC := zExpr + #0;

  rc := sqlite3Fts3InitTokenizer(@g_hash, PChar(zTokC), @pTokenizer, @zErr);
  Check(rc = SQLITE_OK, 'InitTokenizer(' + zTok + ') rc=' + IntToStr(rc));
  if rc <> SQLITE_OK then begin
    sqlite3_free(zErr);
    Exit;
  end;

  nCol := Length(cols);
  for i := 0 to nCol - 1 do begin
    colBuf[i] := cols[i] + #0;
    azCol[i] := PChar(colBuf[i]);
  end;

  { iDefaultCol = nCol matches the fts3_exprtest convention (any column). }
  rc := sqlite3Fts3ExprParse(pTokenizer, 0, @azCol[0], 0, nCol, nCol,
          PChar(zExprC), Length(zExpr), @pExpr, @zErr);
  Check(rc = SQLITE_OK, 'ExprParse([' + zExpr + ']) rc=' + IntToStr(rc));

  if rc = SQLITE_OK then begin
    got := ExprToStr(pExpr);
    Check(got = zExpected,
      '[' + zExpr + '] => "' + got + '" expected "' + zExpected + '"');
  end;

  sqlite3Fts3ExprFree(pExpr);
  sqlite3_free(zErr);
  if pTokenizer <> nil then
    pTokenizer^.pModule^.xDestroy(pTokenizer);
end;

procedure CheckErr(const zTok, zExpr: string; const cols: array of string);
var
  pTokenizer: Psqlite3_tokenizer;
  azCol: array[0..7] of PChar;
  colBuf: array[0..7] of AnsiString;
  nCol, i, rc: cint;
  pExpr: PFts3Expr;
  zErr: PChar;
  zTokC, zExprC: AnsiString;
begin
  pTokenizer := nil; pExpr := nil; zErr := nil;
  zTokC := zTok + #0; zExprC := zExpr + #0;
  rc := sqlite3Fts3InitTokenizer(@g_hash, PChar(zTokC), @pTokenizer, @zErr);
  if rc <> SQLITE_OK then begin sqlite3_free(zErr); Check(False, 'tok'); Exit; end;
  nCol := Length(cols);
  for i := 0 to nCol - 1 do begin colBuf[i] := cols[i] + #0; azCol[i] := PChar(colBuf[i]); end;
  rc := sqlite3Fts3ExprParse(pTokenizer, 0, @azCol[0], 0, nCol, nCol,
          PChar(zExprC), Length(zExpr), @pExpr, @zErr);
  Check(rc <> SQLITE_OK, 'malformed [' + zExpr + '] should error, rc=' + IntToStr(rc));
  Check(pExpr = nil, 'malformed [' + zExpr + '] *ppExpr must be nil');
  sqlite3Fts3ExprFree(pExpr);
  sqlite3_free(zErr);
  if pTokenizer <> nil then pTokenizer^.pModule^.xDestroy(pTokenizer);
end;

var
  db: PTsqlite3;
  rc: cint;
begin
  { A db connection is needed only to make sqlite3_malloc / lookaside-free
    paths used by the parser fully exercised; the parser itself does not
    take a db. }
  db := nil;
  rc := sqlite3_open(':memory:', @db);
  Check(rc = SQLITE_OK, 'open :memory:');

  InitHash;

  { Expected serialisations are from the C oracle (parens=1 mode), which
    matches the engine's compile-time sqlite3_fts3_enable_parentheses=1. }
  DoParse('simple', 'a AND b', ['col'], True,
    'AND {PHRASE 1 0 a} {PHRASE 1 0 b}');
  DoParse('simple', 'a OR b', ['col'], True,
    'OR {PHRASE 1 0 a} {PHRASE 1 0 b}');
  DoParse('simple', 'a NOT b', ['col'], True,
    'NOT {PHRASE 1 0 a} {PHRASE 1 0 b}');
  DoParse('simple', 'a b', ['col'], True,
    'AND {PHRASE 1 0 a} {PHRASE 1 0 b}');
  DoParse('simple', 'a b c', ['col'], True,
    'AND {AND {PHRASE 1 0 a} {PHRASE 1 0 b}} {PHRASE 1 0 c}');
  DoParse('simple', '"a b"', ['col'], True,
    'PHRASE 1 0 a b');
  DoParse('simple', 'a NEAR b', ['col'], True,
    'NEAR/10 {PHRASE 1 0 a} {PHRASE 1 0 b}');
  DoParse('simple', 'a NEAR/3 b', ['col'], True,
    'NEAR/3 {PHRASE 1 0 a} {PHRASE 1 0 b}');
  { Column specifier: col2:hello against 2 columns -> iColumn becomes 1. }
  DoParse('simple', 'col2:hello', ['col1', 'col2'], True,
    'PHRASE 1 0 hello');
  DoParse('simple', '(a OR b) AND c', ['col'], True,
    'AND {OR {PHRASE 1 0 a} {PHRASE 1 0 b}} {PHRASE 1 0 c}');
  { Prefix token. }
  DoParse('simple', 'quick*', ['col'], True,
    'PHRASE 1 0 quick+');
  { Rebalance: a deep OR chain becomes balanced. }
  DoParse('simple', 'a OR b OR c OR d', ['col'], True,
    'OR {OR {PHRASE 1 0 a} {PHRASE 1 0 b}} {OR {PHRASE 1 0 c} {PHRASE 1 0 d}}');

  { Malformed expressions must error and yield a nil tree. }
  CheckErr('simple', 'AND b', ['col']);       { binary op where phrase required }
  CheckErr('simple', '"unterminated', ['col']); { unmatched quote }
  CheckErr('simple', '(a OR b', ['col']);       { unmatched paren }

  sqlite3Fts3HashClear(@g_hash);
  if db <> nil then sqlite3_close(db);

  if g_fail = 0 then begin
    WriteLn('TestFts3Expr: PASS');
    Halt(0);
  end else begin
    WriteLn('TestFts3Expr: FAIL (', g_fail, ' checks failed)');
    Halt(1);
  end;
end.
