# pkgIndex.tcl — generated by src/tests/build_tcl_lib.sh (phase 9.4.7.h).
# Put this directory on ::auto_path, then `package require sqlite3`.
package ifneeded sqlite3 3.53.0 \
    [list load [file join $dir libpassqlite3tcl.so] Sqlite3]
